### ISSUE TITLE
Docker deployment mode support

### ISSUE THREAD

**Issue by sunday866** [masastack/MASA.Stack#2]
I hoped that the MASA Stack supports docker to quickly deploy the demo environment

**Comment by doddgu** [comment]
We're waiting for Helm. It is the standard.

**Comment by visualczm** [comment]
@doddgu 感谢提供这样的企业级别应用平台,看起来听不错的。
但是，昨天试了一天硬是没有跑起来。
环境：
![image](https://github.com/masastack/MASA.Stack/assets/22953065/d6bb67e0-ae0e-4387-bd94-bf48634d16b5)

Docker :
![image](https://github.com/masastack/MASA.Stack/assets/22953065/d8738b69-a5d1-421c-b82e-c5ce5bb17650)

各种报错:
![image](https://github.com/masastack/MASA.Stack/assets/22953065/53c46830-b195-4902-9dff-d23259b48e41)
![image](https://github.com/masastack/MASA.Stack/assets/22953065/793eb2ad-fa7e-4416-82b3-c76f0269f0ba)

docker-compose.yaml 有空格导致报错。
![eff5cb7152e2901b7a93972b23e78b7](https://github.com/masastack/MASA.Stack/assets/22953065/6df0a6c1-55ef-4777-b4fd-64554910e4ad)
